# Generated by Django 3.2.5 on 2021-08-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True)),
                ('Bio', models.CharField(blank=True, max_length=200, null=True)),
                ('Courses', models.CharField(blank=True, max_length=30, null=True)),
                ('email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.PositiveBigIntegerField(blank=True, null=True)),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('Contract', models.FileField(blank=True, null=True, upload_to='')),
                ('Date_Hired', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
