# Generated by Django 3.2.5 on 2021-09-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Contract',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Date_Hired',
            new_name='date_hired',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
