# Generated by Django 3.2.5 on 2021-09-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=12, null=True)),
                ('last_name', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=12, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=12, null=True)),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='')),
                ('date_of_enrollment', models.DateField(blank=True, null=True)),
                ('laptop_number', models.CharField(blank=True, max_length=10, null=True)),
                ('course_name', models.CharField(blank=True, max_length=12, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('language', models.CharField(blank=True, choices=[('E', 'English'), ('K', 'Kiswahili'), ('K', 'Kisudi')], max_length=3, null=True)),
            ],
        ),
    ]
